### ISSUE TITLE
target

### ISSUE THREAD

**Issue by cummins24v2** [Carbon05/qb-rentals#11]
when i got to the ped and i use qb-target it dont pop up in the qb-menu

**Comment by epereza** [comment]
Same issue 
![FiveM_b2612_GTAProcess_OX0jWjuW7z](https://user-images.githubusercontent.com/50680351/170735203-5a0bcbbb-25e9-4103-8113-fd25be5e31b0.jpg)

**Comment by epereza** [comment]
Same issue. I can see the target but no menu appears when pressing it


![FiveM_b2612_GTAProcess_4vHB6IkENO](https://user-images.githubusercontent.com/50680351/170736571-09979c4c-23aa-4d36-963c-481e9fb900ab.jpg)
